name: 'TPDB Complexity'
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: TermCOMP/TPDB-ARI
        sparse-checkout: Complexity_ITS
        path: tpdb-ari

    - run: |
        mv tpdb-ari/Complexity_ITS benchmarks
      shell: bash

