# Creates a docker container where the LoAT root direcotry is mounted to /LoAT
# and triggers a build.

version: "3"

services:
  loat-build:
    image: loat-build:latest
    container_name: loat-build
    security_opt: [seccomp:unconfined]
    cap_add: [SYS_PTRACE]
    volumes:
      - ..:/LoAT
    build:
      context: ..
      dockerfile: docker/build.Dockerfile
    network_mode: host
