#!/bin/bash
trap "" SIGRTMIN

function check() {
    if [ -s $1 ]; then
        value=`cat $1`
        if [[ "$value" = unsat* ]] || [[ "$value" = sat ]]; then
            echo "$value"
            exit 0
        fi
    fi
}

./loat-static --plain --proof-level 0 --mode reachability --format horn --engine abmc $1 2> /dev/null > res1.txt &
./loat-static --plain --proof-level 0 --mode reachability --format horn --engine adcl $1 2> /dev/null > res2.txt &
./loat-static --plain --proof-level 0 --mode reachability --format horn --engine bmc  $1 2> /dev/null > res3.txt &

while true; do
    check res1.txt
    check res2.txt
    check res3.txt
    sleep 1
done;

