name: 'SV Array Benchmarks with negated assertions'
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: LoAT-developers/sv-neg-array-benchmarks
        token: ${{ secrets.GITHUB_TOKEN }}
        path: sv-neg-array-benchmarks

    - run: |
        mkdir benchmarks
        mv sv-neg-array-benchmarks/*.smt2 benchmarks
      shell: bash
