name: 'SV Array Benchmarks with negated assertions'

name: 'SV Array Benchmarks'

inputs:
  pat:
    description: 'personal access token'
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: LoAT-developers/sv-neg-array-benchmarks
        path: sv-neg-array-benchmarks
        token: ${{ inputs.pat }}

    - run: |
        mkdir benchmarks
        mv sv-neg-array-benchmarks/*.smt2 benchmarks
      shell: bash
