name: 'SV Array Benchmarks'
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: loat-developers/sv-array-benchmarks
        token: ${{ secrets.GITHUB_TOKEN }}
        path: sv-array-benchmarks

    - run: |
        mkdir benchmarks
        mv sv-array-benchmarks/*.smt2 benchmarks
      shell: bash
